version: '3'

services:
  api:
    environment:
      - NODE_ENV=production
      - DOCKER_APP=true
    build:
      context: .
      dockerfile: ./Dockerfile-prod
    ports:
      - "80:80"
    links:
      - "redis"
      - "mongo"
    volumes:
      - ./:/usr/src/app/
      - /usr/src/app/node_modules

  redis:
    image: redis

  mongo:
    image: mongo
