version: '3'

services:
  api:
    environment:
      - NODE_ENV=development
      - DOCKER_APP=true
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - "8000:8000"
    links:
      - "redis"
      - "mongo"
    volumes:
      - ./:/usr/src/app/
      - /usr/src/app/node_modules

  redis:
    image: redis

  mongo:
    image: mongo
